### ISSUE TITLE
[Request] Auto-restart plex when a 503 error is received.

### ISSUE THREAD

**Issue by Neaox** [cjmurph/PmsService#26]

**Comment by cjmurph** [comment]
Care to expand on that?

**Comment by Shalar** [comment]
If I understand properly, They would like plex to restart if it is unresponsive, yet the process is still running. I have encountered problems before where using the localhost address of plex gives a 503 error, yet the process still runs. This results in the inability to use plex until the process is killed then started back up.

**Comment by cjmurph** [comment]
Ok, that makes more sense. I'm reluctant as it seems like there's a bug I'll be masking that should be handled by the Plex team. I could spend a bucket of time on it and it'll be sorted in the next release.

**Comment by Shalar** [comment]
I know in my case there is a conflict with my antivirus, that occasionally causes plex to crash occasionally, which is why I'm using this, so that way it will auto restart plex when it stops. It used to be that plex would kill my antivirus rather than the other way around, and then the antivirus company fixed the problem, and now plex crashes. Occasionally instead of crashing I get 503 errors.

**Comment by cjmurph** [comment]
I'm closing this as I don't like masking other bugs, this is one for the plex team to resolve
