### ISSUE TITLE
[Suggestion] A Way to Make Plex Updates Work Correctly

### ISSUE THREAD

**Issue by DWSR** [cjmurph/PmsService#4]
So, I noticed that the way that Plex does "automagic" updates is that it pulls down the new installer to %LOCALAPPDATA%\Plex Media Server\Updates<build>. It would be pretty easy to simply check for a folder that's been accessed within the last couple minutes and simply allow Plex to come back up on its own (or simply wait longer. Say 10 minutes?) rather than trying to restart it immediately.

**Comment by sa2000a** [comment]
I presume this will be a user configurable service option. 

I run the service in a non-admin account and i use a different account for all installs/uninstalls. I would not want to use the service windows account with elevated privileges to install as we have had issues before with that being done and a proper admin account would be recommended. 

With so many issues users encounter with upgrades, i prefer myself to be in full control. Shut down the service. check all plex media server processes terminated. Then run the upgrade.

**Comment by cjmurph** [comment]
If I had control of all the code, I'd do it. Since most of the activity is out of my control, I'd rather not.

The safest approach is to leave it as is. I'd want to start a dialogue with the plex team if this were to be undertaken.

**Comment by DWSR** [comment]
I can certainly understand the apprehension regarding this feature. This feature would really be outside of their scope, though, since they don't "support" running Plex as a Windows service in the first place. I wonder, though, if they could do it by changing the installer flow. Instead of Plex shutting down, launching the installer, then relaunching, the installer could shut down Plex and then relaunch it instead. Hrm. Food for thought. I'll probably suggest it on the forums. It would be nice if Plex were FOSS.

**Comment by cjmurph** [comment]
The workflow for applying the update would need to be thrashed out thoroughly, probably including a system restart.
The primary issue is that anything launched by the service is executed in session 0.
If there are any issues during install and it pops a dialogue up (this has happened to me while trying the auto update feature of plex) the user will never be able to get to it.

Personally, at this stage, I'd like a command line argument sent to Plex to advise them that they are running as a service, then, they can disable the update now button in the web interface. maybe keep an alert there to tell the user a new version is available, but don't give the user the option to install it.

If you want to discuss this further, I think it's better to start a thread on the Plex forums and get in a conversation with the plex team.

**Comment by cjmurph** [comment]
I've been in discussions with the plex team to try and resolve thismost likely by disabling it when running as a service. There are many problems with it, I need to test more, however the service runs in session 0, and that's not an interactive session. if the installer needs UAC elevation, you're stuck. If the installer needs any user input you're stuck. I'd like to close this issue because I feel at this stage, making it actually work is not feasible.

**Comment by Spamme1** [comment]
Yes it would be nice if plex could update itself also when it runs as a service, but also an option to update plex in the menu of the tray icon of the plex service would be nice.
The plex service tray run under the logged in user account, which hasn't the problem of a service with the session 0. 
The question is: Does the plex service know the installed version of plex? Can it determinate, if a newer version is available online and download it? 
Then stop the service, launch the installer and restart the service?
Another question: has the plex installer a quiet mode? So that the user doesn't have to click any button.
And I forget it always, remove plex from the startup programs, this means change the registry, although it would be nicer if this option would be available in the installer.

**Comment by 3van** [comment]
The tray icon application could be modified to periodically check for a new Plex installer. The update feed is at https://plex.tv/updater/products/1/check.xml?build=windows-i386&channel=8&distribution=english&version=0.9.15.0.1621-344f193 (substituting appropriate strings, of course). `channel=8` gets you the PlexPass downloads too if you've logged in to plex.tv already.

I don't really want to write all the logic to handle logins to plex.tv right now (so it would only work for the publicly-available updates), but it wouldn't be too hard to have the tray app issue a notification when there's an update and offer a context menu item to install it (by downloading the installer, stopping the service, running the installer interactively, and starting the service again).

Would that be useful?

**Comment by cjmurph** [comment]
Hold fire. Right now, the problem with auto-updating is that we don't catch that it's happening when initiated from the web interface, when plex is stopped by the installer, we try to restart and break it. Maybe when we catch plex closing, we should be checking to see if the installer application is running, only if it's not found should we restart plex. along with this, perhaps a conversation with the plex team about letting us know somehow (exit code maybe) that plex is stopping to update.

**Comment by bdrumm1234** [comment]
I hate that this never took off 👎

**Comment by jstevenson72** [comment]
It would be trivial to add a menu option to the system tray icon of this project, that simply stops the service, executes the latest installer (already downloaded by Plex), and then restarting the service.  No interaction, conversation, or concern with the Plex team is needed.  As a developer myself, I recognize that sometimes simple solutions are the best.  Please add this, or let someone else do a PR with the suggested fix.

Thanks,

Jason

**Comment by SpyderZT** [comment]
I think that ya'll and this guy should probably talk. :P

https://github.com/TechieGuy12/PlexServerAutoUpdater/

**Comment by thw0rted** [comment]
I've been doing this manually for ages: stop service with PmsService tray icon, start "vanilla" Plex from Start menu, launch web interface, launch updater, tell "vanilla" Plex not to launch at startup and kill it, restart service.  I for one would be thrilled to have a single context-menu item that simply does all of those things.

"Update Plex" could stop the service, wait, start the local-user server, launch the web interface to `#settings/general`, and maybe throw up a modal dialog with instructions to click Update in the web interface, then come back and run "Update Finished" from the service tray context menu after you're done.  "Update Finished" would kill the local-user server, wait, then launch the service server as normal.  Two clicks would be a lot nicer than 5-6, and it wouldn't require breaking the model you use today.

**Comment by cjmurph** [comment]
> I've been doing this manually for ages: stop service with PmsService tray icon, start "vanilla" Plex from Start menu, launch web interface, launch updater, tell "vanilla" Plex not to launch at startup and kill it, restart service. I for one would be thrilled to have a single context-menu item that simply does all of those things.
> 
> "Update Plex" could stop the service, wait, start the local-user server, launch the web interface to `#settings/general`, and maybe throw up a modal dialog with instructions to click Update in the web interface, then come back and run "Update Finished" from the service tray context menu after you're done. "Update Finished" would kill the local-user server, wait, then launch the service server as normal. Two clicks would be a lot nicer than 5-6, and it wouldn't require breaking the model you use today.

Wow, that seems like a long way round. I just go and download the latest installer, stop plex from the service tray, run installer, start plex from service tray.

I think the way to do it is to just work out that plex stopped because the installer stopped it, then don't attempt to restart plex.
The biggest issue is the service restarting plex mid install, also, if the installer throws any windows up, they won't be visible as they're in session 0.
In the short term, you could change the delay time before a restart (it's configurable in the service settings) to five or ten minutes, long enough for the installer to finish and see if that works.

I need to look at this a little closer and come up with an actual solution.
