### ISSUE TITLE
Pass user account and passwords parameter in cli install

### ISSUE THREAD

**Issue by AlBrough** [cjmurph/PmsService#41]
Please can provision be made to pass credentials via cli when installing? 
I have tried using SERVICE_USERNAME, SERVICE_PASSWORD and Username, Password and none seem to work.

**Comment by d8ahazard** [comment]
> Please can provision be made to pass credentials via cli when installing? I have tried using SERVICE_USERNAME, SERVICE_PASSWORD and Username, Password and none seem to work.

Yes, it can. :D

https://github.com/d8ahazard/PmsService/releases/tag/v1.1.8

I've added SERVICE_USERNAME and SERVICE_PASSWORD as optional parameters.

You need to run your install script/process with admin rights, as the MSI installer will not automatically prompt for elevation, and will fail otherwise if run silently.

Proper command syntax would be like so:

```
msiexec.exe /i c:\PlexServiceInstaller.msi /QN SERVICE_USERNAME="MyUsername" SERVICE_PASSWORD="MyPassword"
```
