### ISSUE TITLE
Service port in service settings

### ISSUE THREAD

**Issue by cfjedimaster** [cjmurph/PmsService#66]
This is probably an RTFM (I did check), but when doing Service Settings, I wanted to enable automatic restart, but I can't because the save button is disabled:

![image](https://user-images.githubusercontent.com/393660/197034616-49911363-701f-4a0f-b62b-af3971e5d82a.png)

It would be nice if the dialog here said why, but I figured out it was the service port. What I don't is - is it asking what port Plex is running on? If so, I assume it's the port I see in my Plex Server, Remote Access, right?

**Comment by cjmurph** [comment]
Hi, agreed, it should have validation highlights on the fields that need attention.

The service port is the port used for communication between the tray application and the service, it is not related to Plex itself.

**Comment by cfjedimaster** [comment]
Ok, possibly dumb question, but what should I set it to? Honestly I just want to enable retry. :)

**Comment by SoloTSi97** [comment]
I came here to inquire about the same issue. Apart from validation highlights on the fields that need attention (which would be nice but really aren't strictly blocking the user here), the issue is that the SAVE button is not active _until something that is not zero_ is entered into the Service Port box. The default value of `0` is not good enough to activate the SAVE button.

@cfjedimaster Digging through the code a bit, it looks like `8787` is the default value. I plugged that value into the Server Port box and was able to enable restarts. 👍

https://github.com/cjmurph/PmsService/blob/v1.2.0/PlexServiceTray/TrayApplicationSettings.cs#L78

**Comment by cjmurph** [comment]
The setting on the server and the tray application need to match, the default is 8787.
This is the port the tray application uses to talk to the service, it is not directly related to plex.
This allows you to run the tray application on a different PC to that which plex is running on and control it remotely.
